/* ============================================================
   Script: 03_SEGURIDAD.sql
   Módulo: Seguridad (Asignado a Evelyn)
   Tema: Creación de perfiles, roles, privilegios y usuarios
   ============================================================ */

-- ============================================================
-- 1. CREACIÓN DE PERFIL DE SEGURIDAD
-- ============================================================
CREATE PROFILE PERFIL_BANCARIO LIMIT
    SESSIONS_PER_USER 2
    FAILED_LOGIN_ATTEMPTS 3
    PASSWORD_LIFE_TIME 90
    PASSWORD_GRACE_TIME 5;

-- ============================================================
-- 2. CREACIÓN DE ROLES DEL SISTEMA
-- ============================================================
CREATE ROLE ROL_PAGOS;
CREATE ROLE ROL_AUDITORIA;
CREATE ROLE ROL_GERENCIA;
CREATE ROLE ROL_CAJERO;
CREATE ROLE ROL_JEFE_PAGOS;

-- Privilegio básico para que los usuarios puedan conectarse a la BD
GRANT CREATE SESSION TO ROL_PAGOS, ROL_AUDITORIA, ROL_GERENCIA, ROL_CAJERO, ROL_JEFE_PAGOS;

-- ============================================================
-- 3. ASIGNACIÓN DE PRIVILEGIOS A ROLES
-- ============================================================
-- NOTA: Se asume que este script es ejecutado por el dueño del esquema.

/* Privilegios para el área de PAGOS */
GRANT SELECT ON BENEFICIARIOS TO ROL_PAGOS;
GRANT SELECT ON CUENTAS_BANCARIAS TO ROL_PAGOS;
GRANT SELECT ON CHEQUERAS TO ROL_PAGOS;
GRANT SELECT, UPDATE ON CHEQUES TO ROL_PAGOS;
GRANT EXECUTE ON PR_GENERAR_CHEQUE TO ROL_PAGOS;
GRANT EXECUTE ON PR_MODIFICAR_CHEQUE TO ROL_PAGOS;

/* Privilegios para el área de AUDITORIA */
GRANT SELECT ON CHEQUES TO ROL_AUDITORIA;
GRANT SELECT ON BENEFICIARIOS TO ROL_AUDITORIA;
GRANT EXECUTE ON PR_LIBERAR_CHEQUE TO ROL_AUDITORIA;

/* Privilegios para el área de GERENCIA */
GRANT SELECT ON CHEQUES TO ROL_GERENCIA;
GRANT SELECT ON BENEFICIARIOS TO ROL_GERENCIA;
GRANT EXECUTE ON PR_LIBERAR_CHEQUE TO ROL_GERENCIA;

/* Privilegios para el área de CAJEROS */
GRANT SELECT ON CHEQUES TO ROL_CAJERO;
GRANT SELECT ON CUENTAS_BANCARIAS TO ROL_CAJERO;
GRANT EXECUTE ON PR_ENTREGAR_CHEQUE TO ROL_CAJERO;

/* Privilegios para la JEFATURA DE PAGOS */
GRANT SELECT ON CHEQUES TO ROL_JEFE_PAGOS;
GRANT EXECUTE ON PR_ANULAR_CHEQUE TO ROL_JEFE_PAGOS;


-- ============================================================
-- 4. CREACIÓN DE USUARIOS Y ASIGNACIÓN DE ROLES
-- ============================================================
-- Las contraseñas son de ejemplo, deben cambiarse en producción.

/* Usuarios de PAGOS */
CREATE USER USR_JUANITO IDENTIFIED BY "Umg_Pagos2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_PAGOS TO USR_JUANITO;

CREATE USER USR_PAGOS2 IDENTIFIED BY "Umg_Pagos2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_PAGOS TO USR_PAGOS2;

CREATE USER USR_MARIA_PAGOS IDENTIFIED BY "Umg_Pagos2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_PAGOS TO USR_MARIA_PAGOS;

CREATE USER USR_CARLOS_PAGOS IDENTIFIED BY "Umg_Pagos2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_PAGOS TO USR_CARLOS_PAGOS;

CREATE USER USR_PAGOS_SENIOR IDENTIFIED BY "Umg_Pagos2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_PAGOS TO USR_PAGOS_SENIOR;

/* Usuarios de JEFATURA DE PAGOS */
CREATE USER USR_JEFE_PAGOS IDENTIFIED BY "Umg_Jefe2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_JEFE_PAGOS TO USR_JEFE_PAGOS;

/* Usuarios de AUDITORIA */
CREATE USER USR_AUDITOR IDENTIFIED BY "Umg_Audit2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_AUDITORIA TO USR_AUDITOR;

CREATE USER USR_AUDITOR2 IDENTIFIED BY "Umg_Audit2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_AUDITORIA TO USR_AUDITOR2;

/* Usuarios de GERENCIA */
CREATE USER USR_GERENTE IDENTIFIED BY "Umg_Geren2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_GERENCIA TO USR_GERENTE;

CREATE USER USR_GERENTE2 IDENTIFIED BY "Umg_Geren2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_GERENCIA TO USR_GERENTE2;

/* Usuarios de CAJERO */
CREATE USER USR_CAJERO IDENTIFIED BY "Umg_Caja2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_CAJERO TO USR_CAJERO;

CREATE USER USR_CAJERO2 IDENTIFIED BY "Umg_Caja2026*" PROFILE PERFIL_BANCARIO;
GRANT ROL_CAJERO TO USR_CAJERO2;

COMMIT;